### ISSUE TITLE
Breakdown Gitbook

### ISSUE THREAD

**Issue by BowTiedSirJonathan** [Drey-Finance/actuary-client#17]
[Gitbook](https://drey-finance.gitbook.io/drey-finance/0cuYC1E5XcvDuQ0ktyKG/)

**Comment by BowTiedRadone** [comment]
https://www.notion.so/dreyfinance/Breakdown-Gitbook-d78dccd5d127428db7be3f778827fd1c?pvs=4

**Comment by BowTiedRadone** [comment]
https://www.notion.so/dreyfinance/Breakdown-Gitbook-d78dccd5d127428db7be3f778827fd1c?pvs=4
